RED_R = "0.750000"
RED_G = "0.030000"
RED_B = "0.030000"

FAUNA_PALETTES = { "Fur", "Scale", "Feather", "Underbelly", "Undercoat" }

PALETTE_FILES =
{
  "METADATA\SIMULATION\SOLARSYSTEM\COLOURS\BASECOLOURPALETTES.MBIN",
  "METADATA\SIMULATION\SOLARSYSTEM\COLOURS\LEGACYBASECOLOURPALETTES.MBIN",
  "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BARREN\BARRENCOLOURPALETTES.MBIN",
  "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BARREN\BARRENHQCOLOURPALETTES.MBIN",
  "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BARREN\BARRENPEACOCKCOLOURPALETTES.MBIN",
  "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BARREN\BARRENRUINSCOLOURPALETTES.MBIN",
  "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BURNT\BURNTCOLOURPALETTES.MBIN",
  "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\BURNT\BURNTREMIX\BURNTREMIXCOLOURPALETTES.MBIN",
  "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\DEAD\DEADCOLOURPALETTES.MBIN",
  "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\DESOLATE\DESOLATECOLOURPALETTES.MBIN",
  "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\FROZENCOLOURPALETTES.MBIN",
  "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\FROZEN\FROZENHQCOLOURPALETTES.MBIN",
  "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\GASGIANTS\GASCOLOURPALETTES.MBIN",
  "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\IRRADIATED\IRRADIATEDCOLOURPALETTES.MBIN",
  "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\IRRADIATED\IRRADREMIX\IRRADREMIXCOLOURPALETTES.MBIN",
  "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\JUNGLE\JUNGLECOLOURPALETTES.MBIN",
  "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LAVA\LAVACOLOURPALETTES.MBIN",
  "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LUSHCOLOURPALETTES.MBIN",
  "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LUSHBUBBLESCOLOURPALETTE.MBIN",
  "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LUSHHQCOLOURPALETTE.MBIN",
  "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LUSHROOMACOLOURPALETTE.MBIN",
  "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LUSHROOMBCOLOURPALETTE.MBIN",
  "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LUSHRUINSCOLOURPALETTES.MBIN",
  "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\LUSH\LUSHULTRACOLOURPALETTES.MBIN",
  "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\NOXIOUS\NOXIOUSCOLOURPALETTES.MBIN",
  "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\NOXIOUS\NOXREMIX\NOXREMIXCOLOURPALETTES.MBIN",
  "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\RADIOACTIVE\RADIOCOLOURPALETTES.MBIN",
  "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\SCORCHED\SCORCHCOLOURPALETTES.MBIN",
  "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\SUBZERO\SUBZEROCOLOURPALETTES.MBIN",
  "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\SUBZERO\SUBZREMIX\SUBZREMIXCOLOURPALETTES.MBIN",
  "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\SWAMP\SWAMPCOLOURPALETTES.MBIN",
  "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\TOXIC\TOXICCOLOURPALETTES.MBIN",
  "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\TOXIC\TOXICEGGSCOLOURPALETTES.MBIN",
  "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\TOXIC\TOXICSPORESCOLOURPALETTES.MBIN",
  "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\TOXIC\TOXICTENTACLESCOLOURPALETTES.MBIN",
  "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\WEIRD\BEAMSTONE\BEAMSCOLOURPALETTES.MBIN",
  "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\WEIRD\BONESPIRE\BONESPIRECOLOURPALETTES.MBIN",
  "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\WEIRD\CONTOUR\CONTOURCOLOURPALETTES.MBIN",
  "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\WEIRD\ELBUBBLE\ELBUBBLECOLOURPALETTES.MBIN",
  "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\WEIRD\FRACTALCUBE\FRACTCUBECOLOURPALETTES.MBIN",
  "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\WEIRD\HEXAGON\HEXAGONCOLOURPALETTES.MBIN",
  "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\WEIRD\HOUDINIPROPS\HOUDINIPROPSCOLOURPALETTES.MBIN",
  "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\WEIRD\HYDROGARDEN\HYDROGARDENCOLOURPALETTES.MBIN",
  "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\WEIRD\IRRISHELLS\IRRISHELLSCOLOURPALETTES.MBIN",
  "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\WEIRD\MSTRUCTURES\MSTRUCTCOLOURPALETTES.MBIN",
  "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\WEIRD\SHARDS\SHARDSCOLOURPALETTES.MBIN",
  "METADATA\SIMULATION\SOLARSYSTEM\BIOMES\WEIRD\WIRECELLS\WIRECELLSCOLOURPALETTES.MBIN",
}

PALETTE_CHANGES = {}
for _, palette in ipairs(FAUNA_PALETTES) do
  PALETTE_CHANGES[#PALETTE_CHANGES + 1] =
  {
    ["COMMENT"]             = "Paleta "..palette.." -> rojo carne",
    ["PRECEDING_KEY_WORDS"] = { palette },
    ["REPLACE_TYPE"]        = "ALLINSIDESECTION",
    ["VALUE_CHANGE_TABLE"]  =
    {
      {"R", RED_R},
      {"G", RED_G},
      {"B", RED_B},
    }
  }
end

NMS_MOD_DEFINITION_CONTAINER =
{
["MOD_FILENAME"]    = "HorribleTerror_RedFauna",
["MOD_AUTHOR"]      = "AldrichDDD",
["NMS_VERSION"]     = "6.45",
["MOD_DESCRIPTION"] = "Prueba de validacion - pinta de rojo carne las paletas de piel de la fauna (Fur/Scale/Feather/Underbelly/Undercoat) en todos los biomas.",
["MODIFICATIONS"]   =
  {
    {
      ["MBIN_CHANGE_TABLE"] =
      {
        {
          ["MBIN_FILE_SOURCE"]  = PALETTE_FILES,
          ["MXML_CHANGE_TABLE"] = PALETTE_CHANGES,
        },
      }
    },
  },
}
